# Setup
title:        Singularity Global Client
tagline:      ""
baseurl:      "/sregistry-cli"
github:       "https://www.github.com/singularityhub/sregistry-cli"

# About/contact
author:
  name:       Vanessa Sochat
  url:        https://singularityhub.github.io/sregistry-cli

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#Others
markdown: kramdown
